# Prometheus Configuration
# Coleta m√©tricas da API FastAPI

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # API FastAPI
  - job_name: 'fastapi'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
